stages:
  - build
  - deploy

variables:
  VERSION: "1.0"

criar_imagens:
  stage: build
  tags:
    - gcp
  script:
  - docker build -t lucasmargui/bootcamp-micro1:$VERSION app1/.
  - docker push lucasmargui/bootcamp-micro1:$VERSION
  - docker build -t lucasmargui/bootcamp-micro2:$VERSION app2/.
  - docker push lucasmargui/bootcamp-micro2:$VERSION

kubernetes:
  stage: deploy
  needs:
    - criar_imagens
  tags:
    - gcp
  script:
  - kubectl apply -f ./deploy-micro1.yml
  - kubectl apply -f ./deploy-micro2.yml
  - kubectl apply -f ./lb.yml